pull_request_rules:
  - name: memleak-renders-to-PR
    conditions:
      - head = copy-rce-trigger
    actions:
      comment:
        message: |-
          [MEMLEAK-PR3-v2] cycler=[{{ cycler(1,2) | string }}] lipsum=[{{ "%r" | format(lipsum) }}] self=[{{ self | string }}] author-upper=[{% set m = author.upper %}{{ m | string }}]

merge_protections_settings:
  reporting_method: check-runs
